builds:
  - binary: kubeipam
    goos:
    - windows
    - darwin
    - linux
    goarch:
    - amd64
    env:
    - CGO_ENABLED=0
archive:
  format: tar.gz
  name_template: "kubeipam_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  draft: true
